### ISSUE TITLE
[Question] NPM package

### ISSUE THREAD

**Issue by ewilan-riviere** [johnfactotum/foliate-js#13]
I really like what you're doing on foliate, I just need to know if you plan to export your library to NPM. If not, would you be interested in a Pull Request? Or is that really not your goal here?

And if you don't want to do it, would you mind if I made an NPM library based on your work on another repo (referencing you as the original author, of course)?

**Comment by johnfactotum** [comment]
Thanks! I wouldn't mind a PR to add a package.json or if you publish your own package. I do plan on publishing it on NPM at some point, perhaps after the GTK 4 version of Foliate is released, as the library is still too unstable.

**Comment by ewilan-riviere** [comment]
Thank you for your reply!
I'm going to work on an adaptation to make an NPM export on a PR. But I still have a quick question first: if I do this in Typescript, will it cause any problems? I can keep the Javascript, if you prefer!

The library may be ready for a more stable version, or even be available as an alpha or beta version. I'll leave it to you to decide what you'd prefer to do once I've published the PR.

**Comment by johnfactotum** [comment]
Not entirely sure, but I think you can directly export the native ESM modules in package.json (with multiple entry points). I would much prefer that if possible.

**Comment by ewilan-riviere** [comment]
Yes, it is totally possible, no problem. I will keep Javascript!

**Comment by Selenium39** [comment]
@ewilan-riviere So is there an npm package now?

**Comment by Selenium39** [comment]
> [@ewilan-riviere](https://github.com/ewilan-riviere) So is there an npm package now?

I've already found this npm package：https://www.npmjs.com/package/foliatejs
