### ISSUE TITLE
Add support for vertical epubs

### ISSUE THREAD

**Issue by CaptainDario** [johnfactotum/foliate-js#36]
First of all, this is an awesome package! Thank you!

I was playing around with the reader demo and tried some Japanese epubs. While doing so I noticed that this reader does not seem to support vertical text like this

![image](https://github.com/user-attachments/assets/563a9a3d-c2ed-477f-bb3c-1907ca416331)

Can you add this or am I maybe missing something?

**Comment by johnfactotum** [comment]
Yes, it does support vertical writing. For example you can try opening the [Kusamakura](https://github.com/IDPF/epub3-samples/releases/download/20230704/kusamakura-japanese-vertical-writing.epub.) sample from the [EPUB 3 Samples Project](http://idpf.github.io/epub3-samples/).

**Comment by CaptainDario** [comment]
Is there something I can do to trigger the mode manually?
I tried loading one of my own epubs and it did not display in vertical mode but in horizontal (would actually be a cool feature to toggle between them)

**Comment by CaptainDario** [comment]
I tried the epub you mentioned and indeed it displays in vertical mode.
What could be the reason that my epub does not show in vertical mode?

**Comment by johnfactotum** [comment]
The book needs to set the [`writing-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) property to `vertical-rl` on the root element.

**Comment by CaptainDario** [comment]
Ah, I see, thank you!
I guess I can just toggle this manually from code if I want to ?

**Comment by johnfactotum** [comment]
Currently you can't change it after the section has been loaded. You can change it in the `load` event (a custom event of `<foliate-paginator>` and `<foliate-view>`), but if you change it at any later point, it won't work properly.

**Comment by CaptainDario** [comment]
That's perfectly fine for my use case, thank you!
