### ISSUE TITLE
Can the pdfjsLib use random access of `File` to parse and render PDF document?

### ISSUE THREAD

**Issue by chrox** [johnfactotum/foliate-js#37]
The EPUB parser and renderer has a reasonably low memory footprint by random accessing document file which is neat. I wander if this can be adapted to pdf-js which for now reads the whole file into a ArrayBuffer even just for parsing the document metadata.

**Comment by johnfactotum** [comment]
I've wondered this myself. From https://github.com/mozilla/pdf.js/blob/e1f9fa4ea54246bbfa974ac75720793b9ff9fd12/src/display/api.js#L117, it says it only accepts `TypedArray | ArrayBuffer | Array<number> | string`. But it does support HTTP range requests if you give it a URL. Perhaps one should ask the PDJ.js devs.

**Comment by chrox** [comment]
Nice hint. I will try the HTTP range way.

**Comment by chrox** [comment]
Awesome. It works like a charm.
![image](https://github.com/user-attachments/assets/6902ea34-9870-44b7-9157-753f92939a9b)

**Comment by chrox** [comment]
Let `pdf.js` handle the raw url is a pain. But pdfjsLib also has a `PDFDataRangeTransport` which can be adapted with file slicing to random access the document content. And according to [this comment](https://github.com/mozilla/pdf.js/issues/10452#issuecomment-454347666), the default viewer of `pdf.js` uses this approach.

```
@@ -111,9 +111,15 @@ const makeTOCItem = item => ({
 })

 export const makePDF = async file => {
-    const data = new Uint8Array(await file.arrayBuffer())
+    const initialData = await file.slice(0, 4096).arrayBuffer()
+    const transport = new pdfjsLib.PDFDataRangeTransport(file.size, initialData)
+    transport.requestDataRange = (begin, end) => {
+        file.slice(begin, end).arrayBuffer().then(chunk => {
+            transport.onDataRange(begin, chunk)
+        })
+    }
     const pdf = await pdfjsLib.getDocument({
-        data,
+        range: transport,
         cMapUrl: pdfjsPath('cmaps/'),
         standardFontDataUrl: pdfjsPath('standard_fonts/'),
         isEvalSupported: false,
```

In this way well structured PDF document can be loaded progressively aka. lazy loading only the data for pages that is about to be rendered. If this approach is sound and reasonable I can send a PR for this.
