### ISSUE TITLE
Render the whole chapters on one page?

### ISSUE THREAD

**Issue by theowenyoung** [johnfactotum/foliate-js#6]
Hi, 

Can I render the whole epub pages at one page?

**Comment by johnfactotum** [comment]
If you mean continuous scrolling, that's not supported. Currently, the paginator only supports showing one chapter at a time.

**Comment by theowenyoung** [comment]
Thanks.  Maybe not  continuous scrolling, there is an example: https://1paragraph.app/

this tool can render the whole book at a time.

**Comment by johnfactotum** [comment]
Well, if you want to render everything on the same page at once, you can manually iterate through each object in the `sections` array, call `load()` , and fetch the blob URLs. This will give you the full HTML of each chapter. Then you should be able to append all the content onto the page.
